-- ========================================
-- MÓDULO "CONFIGURACIÓN" — tabla "permisos_rol". Corre esto UNA VEZ
-- en el SQL Editor del proyecto Supabase PRINCIPAL de la plataforma
-- (rmlilqdhxbhpwkysucaz), DESPUÉS de roles-app.sql (usa
-- public.roles_app para el seed inicial).
-- ========================================
-- Reemplaza los "if(sesion.rol !== 'Administrador')" escritos a mano
-- en cada módulo por una tabla: para cada rol, qué módulos del Panel
-- Principal ve, y (para los 3 módulos que internamente son "suites"
-- de varias pantallas) cuáles de esas pantallas internas ve.
--
-- Una fila con submodulo_key = '' controla el módulo completo (la
-- tarjeta del Panel Principal / si puede entrar). Una fila con
-- submodulo_key distinto de '' controla una pantalla puntual DENTRO
-- de un módulo que tiene varias:
--   checklist-5s      -> carga-mensual, colaboradores-activos,
--                         fotos-colaboradores, preguntas-checklist,
--                         reporte-checklist, promotor-5s
--   checklist-equipos -> lista-equipos, preguntas, resumen
--   planificacion-avance -> planificado, recursos, replanificacion,
--                         sap, dashboard, horahora, dialogodiario,
--                         productividad (mismas keys que ya usa
--                         planificacion-avance.js en abrirModulo()).
-- El resto de módulos (Usuarios, Skill Matrix, Reconocimiento, etc.)
-- son de una sola pantalla: solo tienen la fila submodulo_key = ''.
--
-- El rol "Administrador" siempre tiene acceso a todo — eso se
-- resuelve en el código (shared/auth.js, función tienePermiso), no
-- acá, así un módulo nuevo nunca deja afuera sin querer al admin.

create table if not exists public.permisos_rol (

    id bigint generated by default as identity primary key,
    rol text not null,
    modulo_key text not null,
    submodulo_key text not null default '',
    habilitado boolean not null default true,

    unique (rol, modulo_key, submodulo_key)

);

-- ========================================
-- SEED — refleja exactamente los permisos que ya existían escritos a
-- mano en el código al momento de crear esta tabla, para que migrar
-- a este sistema no le cambie el acceso a nadie de un día para otro.
-- Administrador no necesita fila acá (ver nota arriba), por eso el
-- "case" de abajo no lo menciona: si alguna vez se cuela una fila con
-- rol Administrador da lo mismo, el código la ignora.
-- ========================================

insert into public.permisos_rol (rol, modulo_key, submodulo_key, habilitado)
select
    r.nombre,
    m.modulo_key,
    m.submodulo_key,
    case
        when r.nombre = 'Supervisor' then m.supervisor
        when r.nombre = 'Coordinador QHSE' then m.qhse
        else m.otros
    end
from public.roles_app r
cross join (
    values
        -- modulo_key, submodulo_key, supervisor, qhse, otros_roles
        ('checklist-5s', '', true, false, false),
        ('checklist-5s', 'carga-mensual', true, false, false),
        ('checklist-5s', 'colaboradores-activos', true, false, false),
        ('checklist-5s', 'fotos-colaboradores', true, false, false),
        ('checklist-5s', 'preguntas-checklist', true, false, false),
        ('checklist-5s', 'reporte-checklist', true, false, false),
        ('checklist-5s', 'promotor-5s', true, false, false),

        ('checklist-higiene', '', true, true, false),

        ('checklist-equipos', '', true, true, false),
        ('checklist-equipos', 'lista-equipos', true, true, false),
        ('checklist-equipos', 'preguntas', true, true, false),
        ('checklist-equipos', 'resumen', true, true, false),

        ('reporte-anomalias', '', false, false, false),

        ('planificacion-avance', '', true, true, true),
        ('planificacion-avance', 'planificado', true, true, true),
        ('planificacion-avance', 'recursos', true, true, true),
        ('planificacion-avance', 'replanificacion', true, true, true),
        ('planificacion-avance', 'sap', true, true, true),
        ('planificacion-avance', 'dashboard', true, true, true),
        ('planificacion-avance', 'horahora', true, true, true),
        ('planificacion-avance', 'dialogodiario', true, true, true),
        ('planificacion-avance', 'productividad', true, true, true),

        ('reconocimiento', '', true, true, true),

        ('skill-matrix', '', false, false, false),
        ('usuarios', '', false, false, false),
        ('usuarios-centro-proyectos', '', false, false, false),
        ('toma-lote-supermercados', '', false, false, false),
        ('toma-lote-farmacia', '', false, false, false),
        ('inventario-paletas', '', false, false, false),
        ('inventario-picking', '', false, false, false),
        ('configuracion', '', false, false, false)

) as m(modulo_key, submodulo_key, supervisor, qhse, otros)
where r.nombre <> 'Administrador'
on conflict (rol, modulo_key, submodulo_key) do nothing;

-- Mismo criterio de permisos que roles_app: RLS + policies para "anon".
alter table public.permisos_rol enable row level security;

drop policy if exists "permisos_rol_select_anon" on public.permisos_rol;
drop policy if exists "permisos_rol_insert_anon" on public.permisos_rol;
drop policy if exists "permisos_rol_update_anon" on public.permisos_rol;
drop policy if exists "permisos_rol_delete_anon" on public.permisos_rol;

create policy "permisos_rol_select_anon" on public.permisos_rol for select to anon using (true);
create policy "permisos_rol_insert_anon" on public.permisos_rol for insert to anon with check (true);
create policy "permisos_rol_update_anon" on public.permisos_rol for update to anon using (true) with check (true);
create policy "permisos_rol_delete_anon" on public.permisos_rol for delete to anon using (true);
