-- ========================================
-- MÓDULO "CONFIGURACIÓN" — tabla "roles_app". Corre esto UNA VEZ en
-- el SQL Editor del proyecto Supabase PRINCIPAL de la plataforma
-- (rmlilqdhxbhpwkysucaz) — el mismo que usa "usuarios_app".
-- ========================================
-- Antes, el campo "rol" de usuarios_app era texto libre (ver
-- usuarios.html) y con el tiempo se acumularon variantes del mismo
-- rol escritas distinto ("ASISTENTE ADMINISTRATIVO" vs "Asistente
-- administrativo"). Esta tabla pasa a ser la lista única de roles
-- habilitados: el módulo Configuración administra sus altas/bajas, y
-- el formulario "Agregar Usuario" pasa de un input de texto a un
-- <select> alimentado desde acá.

create table if not exists public.roles_app (

    id bigint generated by default as identity primary key,
    nombre text not null unique,
    activo boolean not null default true

);

-- Roles que ya estaban en uso en usuarios_app al momento de crear
-- esta tabla, fusionando la variante en mayúsculas de "Asistente
-- administrativo" en una sola fila.
insert into public.roles_app (nombre) values
    ('Administrador'),
    ('Supervisor'),
    ('Coordinador QHSE'),
    ('Asistente de Operaciones'),
    ('Practicante de Inventario'),
    ('Analista de almacén'),
    ('Jefe de Facturación'),
    ('Asistente de facturación'),
    ('Asistente administrativo'),
    ('Inventario')
on conflict (nombre) do nothing;

-- Deja a los usuarios que tenían la variante en MAYÚSCULAS apuntando
-- al mismo rol ya sembrado arriba.
update public.usuarios_app
set rol = 'Asistente administrativo'
where rol = 'ASISTENTE ADMINISTRATIVO';

-- Mismo criterio de permisos que el resto de tablas del módulo
-- (ver skill-matrix.sql): RLS habilitado + policies explícitas para
-- el rol "anon", que es con el que pega el frontend.
alter table public.roles_app enable row level security;

drop policy if exists "roles_app_select_anon" on public.roles_app;
drop policy if exists "roles_app_insert_anon" on public.roles_app;
drop policy if exists "roles_app_update_anon" on public.roles_app;
drop policy if exists "roles_app_delete_anon" on public.roles_app;

create policy "roles_app_select_anon" on public.roles_app for select to anon using (true);
create policy "roles_app_insert_anon" on public.roles_app for insert to anon with check (true);
create policy "roles_app_update_anon" on public.roles_app for update to anon using (true) with check (true);
create policy "roles_app_delete_anon" on public.roles_app for delete to anon using (true);
