-- ========================================
-- MÓDULO "MARA ALICORP" — script para correr en el
-- SQL Editor del proyecto Supabase (el mismo que usa
-- "Toma de Lote Farmacia": rmlilqdhxbhpwkysucaz).
-- ========================================
-- Este proyecto no tiene migraciones ni ORM: cada tabla se crea a
-- mano en el dashboard de Supabase. Corre este script una sola vez.
--
-- Maestro de materiales Alicorp (basado en "MARA_ALCORP_FARMACIA.xlsx"),
-- más simple que el maestro InRetail Pharma (mara_farmacia.sql):
-- codigo, descripción, EAN/UPC, factor de unidad de almacenamiento
-- y unidad de almacenamiento. A diferencia del maestro InRetail
-- Pharma, acá "codigo" SÍ coincide directo con el CODIGO/SKU que se
-- usa en el resto del módulo.

create table if not exists public.mara_alicorp (

    id bigint generated by default as identity primary key,

    codigo text,
    descripcion text,
    ean text,
    factor_unidad_alm numeric,
    unidad_almacenamiento text,

    archivo_origen text,
    cargado_por text,
    created_at timestamptz not null default now()

);

create index if not exists mara_alicorp_codigo_idx on public.mara_alicorp (codigo);

-- ========================================
-- RLS — mismo criterio que el resto del proyecto: la app usa la
-- clave pública (anon) del cliente para todo, sin login propio de
-- Supabase, así que las políticas quedan abiertas a "anon".
-- ========================================

alter table public.mara_alicorp enable row level security;

drop policy if exists "mara_alicorp_select_anon" on public.mara_alicorp;
drop policy if exists "mara_alicorp_insert_anon" on public.mara_alicorp;
drop policy if exists "mara_alicorp_delete_anon" on public.mara_alicorp;

create policy "mara_alicorp_select_anon" on public.mara_alicorp for select to anon using (true);
create policy "mara_alicorp_insert_anon" on public.mara_alicorp for insert to anon with check (true);
create policy "mara_alicorp_delete_anon" on public.mara_alicorp for delete to anon using (true);
