-- ========================================
-- MÓDULO "OC PORTAL CLIENTE" — script para correr en el
-- SQL Editor del proyecto Supabase (el mismo que usa
-- "Toma de Lote Farmacia": rmlilqdhxbhpwkysucaz).
-- ========================================
-- Este proyecto no tiene migraciones ni ORM: cada tabla se crea a
-- mano en el dashboard de Supabase. Corre este script una sola vez.
--
-- Guarda las OC tal como las exporta el portal del cliente
-- (InRetail), una fila por posición/línea de la OC (basado en el
-- Excel "oc.xlsx"). "codigo_proveedor" es el que coincide con el
-- CODIGO/SKU que se usa en el resto del módulo, y "oc" con la
-- ORDEN DE COMPRA de la plantilla de Toma de Lote Farmacia — esto es
-- lo que después se usará para el cruce (aún no implementado, por
-- ahora solo se carga y guarda tal cual).

create table if not exists public.oc_portal_cliente (

    id bigint generated by default as identity primary key,

    oc bigint,
    tipo_oc text,
    clase_documento text,
    cod_lugar_entrega text,
    nombre_lugar_entrega text,
    direccion_entrega text,
    fecha_emision date,
    fecha_vencimiento date,
    posicion bigint,
    inretail_qs text,
    ean text,
    codigo_proveedor text,
    descripcion_producto text,
    empaque text,
    sku_empaque numeric,
    precio_lista numeric,
    desc_1 numeric,
    desc_2 numeric,
    desc_3 numeric,
    desc_4 numeric,
    desc_5 numeric,
    desc_6 numeric,
    precio_final_neto numeric,
    precio_final_con_imp numeric,
    codigo_local_destino text,
    nombre_local_destino text,
    cantidad_sku_solicitada numeric,

    archivo_origen text,
    cargado_por text,
    created_at timestamptz not null default now()

);

create index if not exists oc_portal_cliente_oc_idx on public.oc_portal_cliente (oc);
create index if not exists oc_portal_cliente_codigo_proveedor_idx on public.oc_portal_cliente (codigo_proveedor);

-- ========================================
-- RLS — mismo criterio que el resto del proyecto: la app usa la
-- clave pública (anon) del cliente para todo, sin login propio de
-- Supabase, así que las políticas quedan abiertas a "anon".
-- ========================================

alter table public.oc_portal_cliente enable row level security;

drop policy if exists "oc_portal_cliente_select_anon" on public.oc_portal_cliente;
drop policy if exists "oc_portal_cliente_insert_anon" on public.oc_portal_cliente;
drop policy if exists "oc_portal_cliente_delete_anon" on public.oc_portal_cliente;

create policy "oc_portal_cliente_select_anon" on public.oc_portal_cliente for select to anon using (true);
create policy "oc_portal_cliente_insert_anon" on public.oc_portal_cliente for insert to anon with check (true);
create policy "oc_portal_cliente_delete_anon" on public.oc_portal_cliente for delete to anon using (true);
