-- ========================================
-- MÓDULO "STOCK FÍSICO SAP" — script para correr en el
-- SQL Editor del proyecto Supabase (el mismo que usa
-- "Toma de Lote Farmacia": rmlilqdhxbhpwkysucaz).
-- ========================================
-- Este proyecto no tiene migraciones ni ORM: cada tabla se crea a
-- mano en el dashboard de Supabase. Corre este script una sola vez.
--
-- Guarda el stock físico tal como lo exporta SAP (basado en el Excel
-- "STOCK_PHARMA.xlsx"), una fila por lote/ubicación. El export de
-- SAP no trae Viaje ni OC (es stock de almacén, no de una compra en
-- particular), así que se etiqueta con el Viaje y la OC que el
-- usuario selecciona en la app ANTES de subir el archivo — de ahí
-- que "viaje"/"oc" sean columnas propias y no parte del Excel.
-- "producto" es el que coincide con el CODIGO/SKU que se usa en el
-- resto del módulo. Por ahora solo se carga y guarda — el cruce
-- contra lo escaneado se agregará después.

create table if not exists public.stock_fisico_sap (

    id bigint generated by default as identity primary key,

    viaje bigint not null,
    oc bigint not null,

    tipo_almacen text,
    ubicacion text,
    producto text,
    descripcion_producto text,
    lote text,
    fecha_caducidad date,
    tipo_stock text,
    cantidad_embalada numeric,
    unidad_medida_alt text,
    cantidad numeric,
    fecha_em date,

    archivo_origen text,
    cargado_por text,
    created_at timestamptz not null default now()

);

create index if not exists stock_fisico_sap_viaje_oc_idx on public.stock_fisico_sap (viaje, oc);
create index if not exists stock_fisico_sap_producto_idx on public.stock_fisico_sap (producto);

-- ========================================
-- RLS — mismo criterio que el resto del proyecto: la app usa la
-- clave pública (anon) del cliente para todo, sin login propio de
-- Supabase, así que las políticas quedan abiertas a "anon".
-- ========================================

alter table public.stock_fisico_sap enable row level security;

drop policy if exists "stock_fisico_sap_select_anon" on public.stock_fisico_sap;
drop policy if exists "stock_fisico_sap_insert_anon" on public.stock_fisico_sap;
drop policy if exists "stock_fisico_sap_delete_anon" on public.stock_fisico_sap;

create policy "stock_fisico_sap_select_anon" on public.stock_fisico_sap for select to anon using (true);
create policy "stock_fisico_sap_insert_anon" on public.stock_fisico_sap for insert to anon with check (true);
create policy "stock_fisico_sap_delete_anon" on public.stock_fisico_sap for delete to anon using (true);
