-- ========================================
-- MÓDULO "RECONOCIMIENTO" — script para correr en el
-- SQL Editor del proyecto Supabase de Planificación y Avance
-- (el mismo que usa "colaboradores": iaitqquphjohgsmelhcj).
-- ========================================
-- Este proyecto no tiene migraciones ni ORM: cada tabla se crea a
-- mano en el dashboard de Supabase. Corre este script una sola vez.

create table if not exists public.reconocimientos (

    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),

    -- Datos generales
    anio int not null,
    trimestre text not null check (trimestre in ('Q1','Q2','Q3','Q4')),

    -- Datos del personal evaluado (denormalizados desde "colaboradores"
    -- para que el histórico no cambie si luego editan la ficha maestra).
    -- Sin "references": si corres esto en el proyecto equivocado (el que
    -- no tiene la tabla "colaboradores"), igual se crea sin error. Si
    -- confirmas que SÍ estás en el proyecto correcto (iaitqquphjohgsmelhcj),
    -- puedes agregar la FK después con:
    --   alter table public.reconocimientos
    --     add constraint reconocimientos_colaborador_id_fkey
    --     foreign key (colaborador_id) references public.colaboradores(id);
    colaborador_id bigint,
    dni text not null,
    nombre_completo text not null,
    jefe_inmediato text not null,
    foto text,

    -- COMPROMISO
    ausentismo text not null,
    puntualidad text not null,
    relaciones_companeros text not null,

    -- OPERACIONES
    calidad text not null,
    productividad text not null,
    inventario text not null,

    -- MEJORA CONTINUA
    aplicacion_5s text not null,
    ideas_mejora text not null,
    capacitaciones text not null,

    -- SEGURIDAD
    reporte_ros text not null,
    capacitaciones_qhse text not null,
    actos_inseguros text not null,

    -- MEDIO AMBIENTE
    mejoras_green text not null,
    credito_carbono text not null,
    dialogo_ambiental text not null,

    -- Resultado (ver fórmula/pesos en shared/reconocimiento-config.js,
    -- función calcularNotaReconocimiento — 100% ajustable ahí, no aquí)
    nota_compromiso numeric(3,2) not null,
    nota_operaciones numeric(3,2) not null,
    nota_mejora_continua numeric(3,2) not null,
    nota_seguridad numeric(3,2) not null,
    nota_medio_ambiente numeric(3,2) not null,
    nota numeric(3,1) not null,       -- 0.0 a 5.0
    estado text not null,             -- "Reconocido" / "Sin reconocimiento"

    -- Columna "PE" del listado: no aparece en el formulario de evaluación
    -- de las capturas, así que queda como campo libre editable después
    -- desde la propia tabla (uso a definir por el negocio).
    pe text,

    registrado_por text

);

alter table public.reconocimientos enable row level security;

-- El resto de tablas de este proyecto (colaboradores, turno_colaboradores,
-- planificacion_diaria) se leen/escriben desde el navegador con la
-- publishable key (anon), sin backend propio, así que esta tabla usa
-- las mismas políticas permisivas. Si más adelante quieren restringir
-- quién puede evaluar, ajusten estas políticas (por ejemplo, exigiendo
-- un JWT de Supabase Auth en vez de dejar todo abierto al rol anon).

drop policy if exists "reconocimientos_select_anon" on public.reconocimientos;
drop policy if exists "reconocimientos_insert_anon" on public.reconocimientos;
drop policy if exists "reconocimientos_update_anon" on public.reconocimientos;

create policy "reconocimientos_select_anon"
    on public.reconocimientos for select
    to anon
    using (true);

create policy "reconocimientos_insert_anon"
    on public.reconocimientos for insert
    to anon
    with check (true);

create policy "reconocimientos_update_anon"
    on public.reconocimientos for update
    to anon
    using (true)
    with check (true);

create index if not exists idx_reconocimientos_anio_trimestre
    on public.reconocimientos (anio, trimestre);

create index if not exists idx_reconocimientos_colaborador
    on public.reconocimientos (colaborador_id);
