-- ========================================
-- MÓDULO "MAESTRO MARA FARMACIA" — script para correr en el
-- SQL Editor del proyecto Supabase (el mismo que usa
-- "Toma de Lote Farmacia": rmlilqdhxbhpwkysucaz).
-- ========================================
-- Este proyecto no tiene migraciones ni ORM: cada tabla se crea a
-- mano en el dashboard de Supabase. Corre este script una sola vez.
--
-- Guarda el maestro de materiales de Farmacia (basado en el Excel
-- "MARA_FARMACIA.xlsx" — hoja "MD INRETAIL PHARMA"). Cód. Proveedor
-- es el que coincide con el CODIGO/SKU que se usa en Toma de Lote
-- Farmacia; no es único en el Excel fuente (un mismo material puede
-- tener más de un EAN), así que no se declara unique/PK acá.

create table if not exists public.mara_farmacia (

    id bigint generated by default as identity primary key,

    cod_lab text,
    laboratorio text,
    cod_sap text,
    cod_proveedor text,
    ean_principal text,
    descripcion text,
    codigo_inkaventa text,
    estado text,
    um_base text,
    um_pedido text,
    master_pack numeric,

    archivo_origen text,
    cargado_por text,
    created_at timestamptz not null default now()

);

create index if not exists mara_farmacia_cod_proveedor_idx on public.mara_farmacia (cod_proveedor);
create index if not exists mara_farmacia_cod_sap_idx on public.mara_farmacia (cod_sap);

-- ========================================
-- RLS — mismo criterio que el resto del proyecto: la app usa la
-- clave pública (anon) del cliente para todo, sin login propio de
-- Supabase, así que las políticas quedan abiertas a "anon".
-- ========================================

alter table public.mara_farmacia enable row level security;

drop policy if exists "mara_farmacia_select_anon" on public.mara_farmacia;
drop policy if exists "mara_farmacia_insert_anon" on public.mara_farmacia;
drop policy if exists "mara_farmacia_delete_anon" on public.mara_farmacia;

create policy "mara_farmacia_select_anon" on public.mara_farmacia for select to anon using (true);
create policy "mara_farmacia_insert_anon" on public.mara_farmacia for insert to anon with check (true);
create policy "mara_farmacia_delete_anon" on public.mara_farmacia for delete to anon using (true);
